apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: rsyslog
    spec:
      nodeSelector:
        CSInfrastructure: "true"
      # Allow non-root user to access PersistentVolume
      securityContext:
        fsGroup: 1000
      containers:
      - name: rsyslog
        env:
        - name: TZ
          value: {{ .Values.timezone }}
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        ports:
        - containerPort: 5514
          protocol: UDP
        - containerPort: 6601
          protocol: TCP
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"  # 0.05 CPU
          limits:
            memory: "128Mi"
            cpu: "250m"  # 0.25 CPU
        volumeMounts:
        - mountPath: /etc/rsyslog/rsyslog.conf
          name: configmap-rsyslog-config
          subPath: rsyslog.conf
          readOnly: true
        - mountPath: /custom-cont-init.d/install-rsyslog.sh
          name: configmap-install-rsyslog
          subPath: install-rsyslog.sh
          readOnly: true
        - mountPath: /var/log
          name: mountvarlog
        - mountPath: /var/spool/rsyslog
          name: mountwork
        - mountPath: /custom-services.d/rsyslog
          name: configmap-rsyslog-service
          subPath: rsyslog
          readOnly: true
        - mountPath: /custom-services.d/cron
          name: configmap-cron-service
          subPath: cron
          readOnly: true
        - mountPath: /etc/periodic/daily/daily-syslog-cleanup.sh
          name: configmap-daily-syslog-cleanup
          subPath: daily-syslog-cleanup.sh
          readOnly: true
        - mountPath: /etc/periodic/daily/daily-syslog-compress-old.sh
          name: configmap-daily-syslog-compress-old
          subPath: daily-syslog-compress-old.sh
          readOnly: true
      volumes:
      - name: mountwork
        persistentVolumeClaim:
          claimName: pvc-rsyslog-work
      - name: mountvarlog
        persistentVolumeClaim:
          claimName: pvc-rsyslog-logs
      - name: configmap-cron-service
        configMap:
          name: rsyslog-config
          defaultMode: 0775
          items:
          - key: cron
            path: cron
      - name: configmap-rsyslog-service
        configMap:
          name: rsyslog-config
          defaultMode: 0775
          items:
          - key: rsyslog
            path: rsyslog
      - name: configmap-daily-syslog-cleanup
        configMap:
          name: rsyslog-config
          defaultMode: 0775
          items:
          - key: daily-syslog-cleanup
            path: daily-syslog-cleanup.sh
      - name: configmap-daily-syslog-compress-old
        configMap:
          name: rsyslog-config
          defaultMode: 0775
          items:
          - key: daily-syslog-compress-old
            path: daily-syslog-compress-old.sh
      - name: configmap-rsyslog-config
        configMap:
          name: rsyslog-config
          defaultMode: 0664
          items:
          - key: rsyslog-config-file
            path: rsyslog.conf
      - name: configmap-install-rsyslog
        configMap:
          name: rsyslog-config
          defaultMode: 0775
          items:
          - key: rsyslog-install
            path: install-rsyslog.sh
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rsyslog
#   namespace: production
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: rsyslog-int.{{ .Values.dns.name }}
#     service.beta.kubernetes.io/azure-dns-label-name: rsyslog-int
#     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
#     service.beta.kubernetes.io/azure-pls-create: "true"
#     # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "Server_AKS_syslog"
#     # service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.230.64.29
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 601
#     targetPort: 6601
#     name: rsyslog-tcp
#     protocol: TCP
#   selector:
#     app: rsyslog
---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog
  namespace: production
  annotations:
    external-dns.alpha.kubernetes.io/hostname: syslog{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{ .Values.dns.name }}
    service.beta.kubernetes.io/azure-dns-label-name: calvincs-syslog{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}
spec:
  type: LoadBalancer
  ports:
  - port: 601
    targetPort: 6601
    name: rsyslog-tcp
    protocol: TCP
  selector:
    app: rsyslog
