kind: ConfigMap
apiVersion: v1
metadata:
  name: rsyslog-config
data:
  rsyslog-install: |
    #!/bin/bash
    echo "**** installing rsyslog ****"
    apk add --no-cache rsyslog
  rsyslog-config-file: |
    # Provides UDP syslog reception
    $ModLoad imudp.so
    $UDPServerRun 5514
    
    # Provides TCP syslog reception
    $ModLoad imtcp.so
    $InputTCPServerRun 6601

    # WorkingDirectory
    $WorkDirectory /var/spool/rsyslog

    # Templates for files
    $template DynamicFile,"/var/log/messages-%timegenerated:::date-year%%timegenerated:::date-month%%timegenerated:::date-day%"
    *.* -?DynamicFile
  rsyslog: |
    #!/usr/bin/with-contenv bash
    /usr/sbin/rsyslogd -n -d -f /etc/rsyslog/rsyslog.conf
  cron: |
    #!/usr/bin/with-contenv bash
    /usr/sbin/crond -f -S -l 0 -c /etc/crontabs
  daily-syslog-cleanup: |
    #!/usr/bin/with-contenv bash
    /usr/bin/find /var/log -type f -name messages* -mtime +30 -delete
  daily-syslog-compress-old: |
    #!/usr/bin/with-contenv bash
    /usr/bin/find /var/log -type f -name messages* ! -name 'messages*.gz' -mtime +2 -exec gzip {} \;
