apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rsyslog-logs
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rsyslog-work
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pvc-rsyslog-config
#spec:
#  accessModes:
#  - ReadWriteOnce
#  storageClassName: managed-csi
#  resources:
#    requests:
#      storage: 1Gi
